mqtt:
  broker_ip: localhost
  port: 1883
  topic_base: home

influxdb:
  ip: localhost
  port: 8086
  bucket: sensor_data
  org: iot_project
  token: 3WBNOqEAbSQJWAYWLvm-Cs0_PFgOk4Ir-MFOdknVzSgiEYcGhPpJGEJGaOqyKEOjKGB7IHCOTAyzGPU-yqkPOw==